<?php

namespace AppBundle\Repository;

/**
 * plantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantRepository extends \Doctrine\ORM\EntityRepository
{
}
