<?php

namespace AppBundle\Repository;

/**
 * SoilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoilRepository extends \Doctrine\ORM\EntityRepository
{
}
