<?php

namespace AppBundle\Repository;

/**
 * WateringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WateringRepository extends \Doctrine\ORM\EntityRepository
{
}
